spring:
  application:
    name: agroiq-sensor-simulator
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  simulator:
    agriculture:
      tick-rate-ms: 5000
      anomaly-probability: 0.05
      anomaly-duration-ms: 30000
